name       : v4l2loopback
version    : 0.10.0
release    : 32
source     :
    - https://github.com/umlaeute/v4l2loopback/archive/v0.10.0.tar.gz : 9bb1e8d544019bead20813877415ae974fbc22f87c69772984a4abac433f36dd
license    : GPL-2.0
component  : kernel.driver
summary    :
    - A kernel module to create V4L2 loopback devices
    - current : v4l2loopback package for linux-current
    - common : Common components for v4l2loopback packages
description: |
    A kernel module to create V4L2 loopback devices
builddeps  :
    - help2man
    - linux-lts
    - linux-lts-headers
    - linux-current
    - linux-current-headers
rundeps    :
    - linux-lts
    - v4l2loopback-common
    - current :
        - linux-current
        - v4l2loopback-common
permanent  :
    - /lib/modules
patterns   :
    - common :
        - /usr/bin
        - /usr/share/man
    - current : /lib/modules/*.current
setup      : |
    pushd ..
    cp -a v4l2loopback-${version} lts-build
    cp -a v4l2loopback-${version} current-build
build      : |
    pushd lts-build
    %make KERNELRELEASE=%kernel_version_lts%
    pushd ../current-build
    %make KERNELRELEASE=%kernel_version_current%
install    : |
    pushd lts-build
    export KERN=%kernel_version_lts%
    %make KERNELRELEASE=$KERN install-utils install-man DESTDIR=$installdir PREFIX=/usr
    install -D -m 00755 v4l2loopback.ko $installdir/lib/modules/$KERN/extra/v4l2loopback.ko
    pushd ../current-build
    export KERN=%kernel_version_current%
    install -D -m 00755 v4l2loopback.ko $installdir/lib/modules/$KERN/extra/v4l2loopback.ko
