name       : v4l2loopback
version    : 0.10.0
release    : 15
source     :
    - https://github.com/umlaeute/v4l2loopback/archive/v0.10.0.tar.gz : 9bb1e8d544019bead20813877415ae974fbc22f87c69772984a4abac433f36dd
license    : GPL-2.0
component  : kernel.driver
summary    : A kernel module to create V4L2 loopback devices
description: |
    A kernel module to create V4L2 loopback devices
builddeps  :
    - help2man
    - linux-lts
    - linux-lts-headers
build      : |
    %make KERNELRELEASE=%kernel_version_lts%
install    : |
    export KERN=%kernel_version_lts%
    %make KERNELRELEASE=$KERN install-utils install-man DESTDIR=$installdir PREFIX=/usr
    install -D -m 00755 v4l2loopback.ko $installdir/lib/modules/$KERN/extra/v4l2loopback.ko
